name: Node.js CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Init submodules and dependencies
        run: sh init.sh

      - name: Check TypeScript version
        run: npx tsc -v

      - name: Run check
        run: npm run check

      - name: Run check:test
        run: npm run check:test

      - name: Run check:smith
        run: npm run check:smith

      - name: Build
        run: npm run build --if-present
